[agent]
  interval = "1s"
  round_interval = true
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensors_actuators/+"]
  data_format = "json_v2"
  topic_tag = ""

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "sensors_actuators/+"
    measurement = "_/measurement"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      timestamp_key = "time"
      timestamp_format = "unix_ns"
      tags = ["name", "device_name", "is_simulated"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "WDpF25Im48BaRc7bEn0BzCZkDZpPUVmVvjsYz2A0m5LhxJGBTMyf9PElvy7xzWG8N9Zh7-zN9M7-lIbGtofh3g=="
  organization = "iot"
  bucket = "iotBucket"
