{
 "title": "PI2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "4SD - PI2's stopwatch display",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"FOUR_SD\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"] == \"FOUR_SD\")"
    }
   ]
  },
  {
   "title": "BTN - PI2's stopwatch button",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Button\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"] == \"BTN\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value: 0)\n  "
    }
   ]
  },
  {
   "title": "GYR - PI2's gyroscope",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GYRO\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"] == \"GYR\")"
    }
   ]
  },
  {
   "title": "DHT3 - PI2's Temperature and Humidity sensor",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Humidity\" or r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"] == \"DHT3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DUS2 - PI2's Door Ultrasonic Sensor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"UltrasonicSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"] == \"DUS2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DPIR2 - PI2's MotionSensor",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"MotionSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"] == \"DPIR2\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value: 0)\n  "
    }
   ]
  },
  {
   "title": "DS2 - PI2's Door Sensor",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"DoorSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"name\"]  == \"DS2\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value :0)"
    }
   ]
  }
 ]
}