{
 "title": "PI1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DMS - PI1's keypad",
   "type": "table",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"iotBucket\")\n           |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KeypadSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n            |> sort(columns: [\"_time\"], desc: true)"
    }
   ]
  },
  {
   "title": "DBZ1 - PI1's Buzzer",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"BuzzerActuator\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI1\")\n  |> filter(fn: (r) => r[\"name\"] == \"DBZ1\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value: 0)\n  "
    }
   ]
  },
  {
   "title": "DPIR1 - PI1's MotionSensor",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"MotionSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI1\")\n  |> filter(fn: (r) => r[\"name\"] == \"DPIR1\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value: 0)\n  "
    }
   ]
  },
  {
   "title": "DL1 - PI1's Door Light",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"LightActuator\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI1\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value: 0)"
    }
   ]
  },
  {
   "title": "DS1 - PI1's Door Sensor",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"DoorSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI1\")\n  |> filter(fn: (r) => r[\"name\"]  == \"DS1\")\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: true)\n  |> fill(column: \"_value\", value :0)"
    }
   ]
  },
  {
   "title": "DUS1 - PI1's Door Ultrasonic Sensor",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 73 },
   "targets": [
    {
     "query": "from(bucket: \"iotBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"UltrasonicSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"PI1\")\n  |> filter(fn: (r) => r[\"name\"] == \"DUS1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}